// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqzNB6duUWOv4WACZaN0gYvszt97_3Thk',
    appId: '1:465196584764:web:e35d4b5a466c24c3d29839',
    messagingSenderId: '465196584764',
    projectId: 'time-capsule-5ecb5',
    authDomain: 'time-capsule-5ecb5.firebaseapp.com',
    storageBucket: 'time-capsule-5ecb5.firebasestorage.app',
    measurementId: 'G-4L1ZCG6TCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuAb_-KCQEosSyrkofti_Y3GwQ1h33t1k',
    appId: '1:465196584764:android:f172e6b74896e948d29839',
    messagingSenderId: '465196584764',
    projectId: 'time-capsule-5ecb5',
    storageBucket: 'time-capsule-5ecb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbW6-D95cPKG5gqs3hZc-RIriK2crXY0Y',
    appId: '1:465196584764:ios:5521b69c99c26ce4d29839',
    messagingSenderId: '465196584764',
    projectId: 'time-capsule-5ecb5',
    storageBucket: 'time-capsule-5ecb5.firebasestorage.app',
    androidClientId: '465196584764-pqostadol8psdlj403kgnorv198pb9be.apps.googleusercontent.com',
    iosClientId: '465196584764-eiqn93bh1kf0ibaqsdugeqnpnaq5dp4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeCapsule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbW6-D95cPKG5gqs3hZc-RIriK2crXY0Y',
    appId: '1:465196584764:ios:5521b69c99c26ce4d29839',
    messagingSenderId: '465196584764',
    projectId: 'time-capsule-5ecb5',
    storageBucket: 'time-capsule-5ecb5.firebasestorage.app',
    androidClientId: '465196584764-pqostadol8psdlj403kgnorv198pb9be.apps.googleusercontent.com',
    iosClientId: '465196584764-eiqn93bh1kf0ibaqsdugeqnpnaq5dp4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeCapsule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqzNB6duUWOv4WACZaN0gYvszt97_3Thk',
    appId: '1:465196584764:web:40d99a3a72ed1cdad29839',
    messagingSenderId: '465196584764',
    projectId: 'time-capsule-5ecb5',
    authDomain: 'time-capsule-5ecb5.firebaseapp.com',
    storageBucket: 'time-capsule-5ecb5.firebasestorage.app',
    measurementId: 'G-Z0710Z5KL3',
  );
}
